# Generated by Django 2.0.3 on 2018-03-10 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2018, 3, 10, 4, 54, 58, 601375, tzinfo=utc))),
            ],
        ),
    ]
